// src/game/constants.ts
export const GAME_CONSTANTS = {
  SHIP_ACCELERATION: 200,
  ROTATION_SPEED: 3,
  MAX_VELOCITY: 400,
  BOOST_MULTIPLIER: 2,
  MAX_BOOST_FUEL: 100,
  BOOST_CONSUMPTION_RATE: 50,
  BOOST_RECHARGE_RATE: 20,
  PROJECTILE_SPEED: 300,
  PROJECTILE_COOLDOWN: 1,
  PROJECTILE_LIFETIME: 100000,
  DRAG: 0.99,
  WORLD_HEIGHT: 3000,
  WORLD_WIDTH: 3000,
} as const
